// Extracts monochrome provider logos from @iconify/json into src/shared/ui/providerLogos.ts,
// so only the logos we use enter the bundle. Every logo is drawn in currentColor.
// Run with `pnpm run logos:providers` after changing the list below.
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const root = dirname(fileURLToPath(import.meta.url));
const iconSet = (name) => JSON.parse(readFileSync(require.resolve(`@iconify/json/json/${name}.json`), "utf8"));

// key → [Iconify set, icon name]. Simple Icons (CC0) first; theSVG (MIT) fills the gaps.
const logos = {
  anthropic: ["simple-icons", "anthropic"],
  claude: ["simple-icons", "claude"],
  openai: ["simple-icons", "openai"],
  gemini: ["simple-icons", "googlegemini"],
  google: ["simple-icons", "google"],
  deepseek: ["simple-icons", "deepseek"],
  xai: ["thesvg", "xai"],
  moonshot: ["simple-icons", "moonshotai"],
  kimi: ["simple-icons", "kimi"],
  qwen: ["simple-icons", "qwen"],
  alibabacloud: ["simple-icons", "alibabacloud"],
  zhipu: ["thesvg", "zhipu"],
  doubao: ["thesvg", "doubao"],
  volcengine: ["thesvg", "volcengine"],
  minimax: ["simple-icons", "minimax"],
  mistral: ["simple-icons", "mistralai"],
  openrouter: ["simple-icons", "openrouter"],
  ollama: ["simple-icons", "ollama"],
  lmstudio: ["simple-icons", "lmstudio"],
  huggingface: ["simple-icons", "huggingface"],
  perplexity: ["simple-icons", "perplexity"],
  stepfun: ["thesvg", "stepfun"],
  baichuan: ["thesvg", "baichuan"],
  hunyuan: ["thesvg", "hunyuan"],
  baidu: ["simple-icons", "baidu"],
  nvidia: ["simple-icons", "nvidia"],
  azure: ["simple-icons", "microsoftazure"],
  aws: ["simple-icons", "amazonwebservices"],
  cloudflare: ["simple-icons", "cloudflare"],
  githubcopilot: ["simple-icons", "githubcopilot"],
};

const sets = new Map();
const entries = Object.entries(logos).map(([key, [setName, iconName]]) => {
  if (!sets.has(setName)) sets.set(setName, iconSet(setName));
  const set = sets.get(setName);
  const icon = set.icons[iconName];
  if (!icon) throw new Error(`${setName}:${iconName} not found`);
  const width = icon.width ?? set.width ?? 24;
  const height = icon.height ?? set.height ?? 24;
  // One ink: any fixed fill or stroke becomes currentColor.
  const body = icon.body.replace(/(fill|stroke)="(?!none)[^"]*"/g, '$1="currentColor"');
  return `  ${key}: logo(${JSON.stringify(body)}, ${width}, ${height}),`;
});

writeFileSync(join(root, "../src/shared/ui/providerLogos.ts"), `// Generated by scripts/provider-logos.mjs from @iconify/json (Simple Icons, CC0; theSVG, MIT).
// Do not edit by hand.
import type { IconifyIcon } from "@iconify/react";

const logo = (body: string, width: number, height: number): IconifyIcon => ({ body, width, height });

export const providerLogos = {
${entries.join("\n")}
} satisfies Record<string, IconifyIcon>;

export type ProviderLogoKey = keyof typeof providerLogos;
`);
console.log(`wrote ${entries.length} provider logos`);
